services:
  upload-manager:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: upload-manager
    ports:
      - "10000:10000"
    environment:
      # 应用配置
      - APP_NAME=单据上传管理系统
      - APP_VERSION=1.0.0
      - HOST=0.0.0.0
      - PORT=10000
      - DEBUG=false

      # 用友云配置 - 必须设置
      - YONYOU_APP_KEY=${YONYOU_APP_KEY}
      - YONYOU_APP_SECRET=${YONYOU_APP_SECRET}
      - YONYOU_BUSINESS_TYPE=yonbip-scm-scmsa
      - YONYOU_AUTH_URL=https://c4.yonyoucloud.com/iuap-api-auth/open-auth/selfAppAuth/base/v1/getAccessToken
      - YONYOU_UPLOAD_URL=https://c4.yonyoucloud.com/iuap-api-gateway/yonbip/uspace/iuap-apcom-file/rest/v1/file

      # 上传配置
      - MAX_FILE_SIZE=10485760
      - MAX_FILES_PER_REQUEST=10

      # 重试配置
      - MAX_RETRY_COUNT=3
      - RETRY_DELAY=2
      - REQUEST_TIMEOUT=30

      # 并发控制
      - MAX_CONCURRENT_UPLOADS=3

      # 数据库配置
      - DATABASE_URL=sqlite:///data/uploads.db

      # 本地文件存储配置
      - LOCAL_STORAGE_PATH=data/uploaded_files

      # Token缓存配置
      - TOKEN_CACHE_DURATION=3600

    volumes:
      # 持久化数据
      - ./data:/app/data
      # 持久化日志
      - ./logs:/app/logs

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:10000/api/health').read()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

    networks:
      - upload-network

networks:
  upload-network:
    driver: bridge
